source 'https://rubygems.org'
ruby '2.1.3'

gem 'rails', '4.1.6'
gem 'sass-rails', '~> 4.0.2'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'bootstrap-sass', '>= 3.1.1'
gem 'devise'
gem 'devise_invitable'
gem 'figaro'
gem 'haml-rails'
gem 'mysql2'
gem 'dynamic_form'

gem 'workflow', git: 'git@github.com:geekq/workflow.git'
gem 'friendly_id', '~> 5.0.0'
gem 'kaminari'
gem 'rails_autolink'
gem 'sitemap_generator'

group :development do
  gem 'capistrano', '~> 3.1.0'
  gem 'capistrano-rails'
  gem 'capistrano-rvm'
  gem 'capistrano-bundler'
  gem 'puma'
  gem 'rails_layout'
  gem 'seed_dump'
  gem 'nokogiri'
end
